'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class client_images

    '''<summary>
    '''hdnImage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnImage As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdnIsNewImage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnIsNewImage As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''btnSavePostback control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSavePostback As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''pnlNoData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlNoData As Global.IAW.controls.IAWPanel

    '''<summary>
    '''IAWLabel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel1 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''IAWLabel2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel2 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''tblOuter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblOuter As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''pnlDataSource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlDataSource As Global.IAW.controls.IAWPanel

    '''<summary>
    '''grdDatasource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdDatasource As Global.IAW.controls.IAWGrid

    '''<summary>
    '''pnlDatasourceImageList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlDatasourceImageList As Global.IAW.controls.IAWPanel

    '''<summary>
    '''btnSortAsc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSortAsc As Global.IAW.controls.IAWHyperLinkButton

    '''<summary>
    '''btnSortDesc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSortDesc As Global.IAW.controls.IAWHyperLinkButton

    '''<summary>
    '''ddlbSort control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlbSort As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtURfilter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtURfilter As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''grdDatasourceImageList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdDatasourceImageList As Global.IAW.controls.IAWGrid

    '''<summary>
    '''pnlImage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlImage As Global.IAW.controls.IAWPanel

    '''<summary>
    '''btnCropSquare control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCropSquare As Global.IAW.controls.IAWLabel

    '''<summary>
    '''btnCropCircle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCropCircle As Global.IAW.controls.IAWLabel

    '''<summary>
    '''btnRotateLeft control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnRotateLeft As Global.IAW.controls.IAWLabel

    '''<summary>
    '''btnRotateRight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnRotateRight As Global.IAW.controls.IAWLabel

    '''<summary>
    '''btnFlipHorizontal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnFlipHorizontal As Global.IAW.controls.IAWLabel

    '''<summary>
    '''btnFlipVertical control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnFlipVertical As Global.IAW.controls.IAWLabel

    '''<summary>
    '''divAccButtons control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divAccButtons As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''btnImageSave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnImageSave As Global.IAW.controls.IAWLabel

    '''<summary>
    '''btnImageCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnImageCancel As Global.IAW.controls.IAWLabel

    '''<summary>
    '''lblDropHere control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDropHere As Global.IAW.controls.IAWLabel

    '''<summary>
    '''btnImageUpload control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnImageUpload As Global.IAW.controls.IAWLabel

    '''<summary>
    '''IAWLabel5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel5 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''lblUploadedDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUploadedDate As Global.IAW.controls.IAWLabel

    '''<summary>
    '''btnRemoveImage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnRemoveImage As Global.IAW.controls.IAWHyperLinkButton

    '''<summary>
    '''btnRestoreImage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnRestoreImage As Global.IAW.controls.IAWHyperLinkButton

    '''<summary>
    '''popRemoveImage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents popRemoveImage As Global.IAW.controls.IAWPanel

    '''<summary>
    '''IAWLabel4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel4 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''btnRemoveImageOk control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnRemoveImageOk As Global.IAW.controls.IAWHyperLinkButton

    '''<summary>
    '''btnRemoveImageCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnRemoveImageCancel As Global.IAW.controls.IAWHyperLinkButton

    '''<summary>
    '''popRemoveImageFake control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents popRemoveImageFake As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''mpeRemoveImage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mpeRemoveImage As Global.AjaxControlToolkit.ModalPopupExtender

    '''<summary>
    '''popRestoreImage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents popRestoreImage As Global.IAW.controls.IAWPanel

    '''<summary>
    '''IAWLabel46 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel46 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''btnRestoreImageOk control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnRestoreImageOk As Global.IAW.controls.IAWHyperLinkButton

    '''<summary>
    '''btnRestoreImageCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnRestoreImageCancel As Global.IAW.controls.IAWHyperLinkButton

    '''<summary>
    '''popRestoreImageFake control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents popRestoreImageFake As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''mpeRestoreImage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mpeRestoreImage As Global.AjaxControlToolkit.ModalPopupExtender
End Class
