'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class client_settings

    '''<summary>
    '''hdnChangesPending control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnChangesPending As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdnAttrib control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnAttrib As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''ddlbFont control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlbFont As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''hdnLogo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnLogo As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdnLogofilename control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnLogofilename As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdnHeaderIconsFilter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnHeaderIconsFilter As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdnHeaderIconsHoverFilter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnHeaderIconsHoverFilter As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdnBodyIconsFilter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnBodyIconsFilter As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdnBodyIconsHoverFilter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnBodyIconsHoverFilter As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdnCheckboxFilter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnCheckboxFilter As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdnBgType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnBgType As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdnBgContent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnBgContent As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdnBgImageName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnBgImageName As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdnPrevBgImage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnPrevBgImage As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdnBgStructure control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnBgStructure As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''pnlDisplay control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlDisplay As Global.IAW.controls.IAWPanel

    '''<summary>
    '''tcBranding control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tcBranding As Global.AjaxControlToolkit.TabContainer

    '''<summary>
    '''tpBranding control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tpBranding As Global.IAW.controls.IAWTabPanel

    '''<summary>
    '''pnlGrdBrand control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlGrdBrand As Global.IAW.controls.IAWPanel

    '''<summary>
    '''grdBrand control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdBrand As Global.IAW.controls.IAWGrid

    '''<summary>
    '''btnThemeSelect control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnThemeSelect As Global.IAW.controls.IAWHyperLinkButton

    '''<summary>
    '''TabContainer1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TabContainer1 As Global.AjaxControlToolkit.TabContainer

    '''<summary>
    '''tpGeneral control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tpGeneral As Global.IAW.controls.IAWTabPanel

    '''<summary>
    '''chooseFile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chooseFile As Global.IAW.controls.IAWHyperLinkButton

    '''<summary>
    '''labFileName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents labFileName As Global.IAW.controls.IAWLabel

    '''<summary>
    '''FileUpload1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FileUpload1 As Global.System.Web.UI.WebControls.FileUpload

    '''<summary>
    '''cbAdvanced control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbAdvanced As Global.IAW.controls.IAWCheckBox

    '''<summary>
    '''trLogoPreview control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trLogoPreview As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''logoPreview control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents logoPreview As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''trLogoColours control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trLogoColours As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''IAWLabel37 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel37 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''IAWLabel23 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel23 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''logoNormalColour control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents logoNormalColour As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''IAWLabel33 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel33 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''logoLighterColour control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents logoLighterColour As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''IAWLabel36 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel36 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''logoDarkerColour control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents logoDarkerColour As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''pAdvanced control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pAdvanced As Global.IAW.controls.IAWPanel

    '''<summary>
    '''IAWLabel50 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel50 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''bannerTextColour control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bannerTextColour As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''bannerBgColour control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bannerBgColour As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''IAWLabel68 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel68 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''bannerIconsHoverColour control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bannerIconsHoverColour As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''IAWLabel60 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel60 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''ddlbBodyBackgroundType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlbBodyBackgroundType As Global.IAW.controls.IAWDropDownList

    '''<summary>
    '''IAWLabel16 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel16 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''bodyBgColour control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bodyBgColour As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''IAWLabel62 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel62 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''ddlbBodyBackgroundImage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlbBodyBackgroundImage As Global.IAW.controls.IAWDropDownList

    '''<summary>
    '''IAWLabel67 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel67 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''ddlbBodyBackgroundGradient control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlbBodyBackgroundGradient As Global.IAW.controls.IAWDropDownList

    '''<summary>
    '''IAWLabel52 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel52 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''textColour control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents textColour As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''pSimplified control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pSimplified As Global.IAW.controls.IAWPanel

    '''<summary>
    '''IAWLabel40 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel40 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''simpBannerBgColour control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents simpBannerBgColour As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''IAWLabel39 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel39 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''simpPrincipal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents simpPrincipal As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''simpLightPrincipal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents simpLightPrincipal As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''IAWLabel41 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel41 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''simpContentArea control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents simpContentArea As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''simpDarkContextArea control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents simpDarkContextArea As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''IAWLabel43 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel43 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''simpText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents simpText As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''simpLightText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents simpLightText As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''IAWLabel45 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel45 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''simpExceptions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents simpExceptions As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''tpContents control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tpContents As Global.IAW.controls.IAWTabPanel

    '''<summary>
    '''IAWLabel49 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel49 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''contentAreaBgColour control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents contentAreaBgColour As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''IAWLabel55 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel55 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''legendTextColour control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents legendTextColour As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''legendBgColour control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents legendBgColour As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''legendBorderColour control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents legendBorderColour As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''IAWLabel56 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel56 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''tabsTextColour control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tabsTextColour As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''tabsBgColour control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tabsBgColour As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''IAWLabel64 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel64 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''tabsTextHoverColour control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tabsTextHoverColour As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''tabsBgHoverColour control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tabsBgHoverColour As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''IAWLabel13 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel13 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''selectedTabsTextColour control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents selectedTabsTextColour As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''selectedTabsBgColour control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents selectedTabsBgColour As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''IAWLabel51 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel51 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''linkTextColour control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents linkTextColour As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''linkBgColour control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents linkBgColour As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''IAWLabel63 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel63 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''linkTextHoverColour control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents linkTextHoverColour As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''linkBgHoverColour control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents linkBgHoverColour As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''IAWLabel53 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel53 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''inptFieldTextColour control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents inptFieldTextColour As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''inptFieldBgColour control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents inptFieldBgColour As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''inptFieldBorderColour control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents inptFieldBorderColour As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''IAWLabel54 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel54 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''inptFieldFocusBgColour control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents inptFieldFocusBgColour As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''IAWLabel66 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel66 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''menuItemTextColour control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents menuItemTextColour As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''menuItemBgColour control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents menuItemBgColour As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''lblMenuIcon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMenuIcon As Global.IAW.controls.IAWLabel

    '''<summary>
    '''menuButtonColour control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents menuButtonColour As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''IAWLabel42 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel42 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''menuIconColour control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents menuIconColour As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''IAWLabel6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel6 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''draggablesTextColour control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents draggablesTextColour As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''draggablesBGColour control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents draggablesBGColour As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''draggablesBorderColour control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents draggablesBorderColour As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''IAWLabel12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel12 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''draggablesTextHoverColour control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents draggablesTextHoverColour As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''draggablesBGHoverColour control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents draggablesBGHoverColour As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''draggablesBorderHoverColour control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents draggablesBorderHoverColour As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''IAWLabel61 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel61 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''imageCharactersColour control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imageCharactersColour As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''imageCharactersHighlightColour control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imageCharactersHighlightColour As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''IAWLabel81 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel81 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''checkboxColour control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents checkboxColour As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''tpLists control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tpLists As Global.IAW.controls.IAWTabPanel

    '''<summary>
    '''IAWLabel57 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel57 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''listHeaderTextColour control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents listHeaderTextColour As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''listHeaderBgColour control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents listHeaderBgColour As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''IAWLabel8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel8 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''listHeaderIconsColour control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents listHeaderIconsColour As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''listHeaderIconsHoverColour control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents listHeaderIconsHoverColour As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''IAWLabel11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel11 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''listRowColour control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents listRowColour As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''listRowBgColour control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents listRowBgColour As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''IAWLabel28 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel28 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''listAltRowColour control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents listAltRowColour As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''listAltRowBgColour control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents listAltRowBgColour As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''IAWLabel58 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel58 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''selectedRowTextColour control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents selectedRowTextColour As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''selectedRowBgColour control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents selectedRowBgColour As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''IAWLabel59 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel59 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''selectedRowTextHoverColour control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents selectedRowTextHoverColour As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''selectedRowBgHoverColour control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents selectedRowBgHoverColour As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''IAWLabel10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel10 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''listBodyIconsColour control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents listBodyIconsColour As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''listBodyIconsHoverColour control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents listBodyIconsHoverColour As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''tpBackgrounds control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tpBackgrounds As Global.IAW.controls.IAWTabPanel

    '''<summary>
    '''grdBackgrounds control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdBackgrounds As Global.IAW.controls.IAWGrid

    '''<summary>
    '''tpChart control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tpChart As Global.IAW.controls.IAWTabPanel

    '''<summary>
    '''TabContainer3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TabContainer3 As Global.AjaxControlToolkit.TabContainer

    '''<summary>
    '''IAWTabPanel4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWTabPanel4 As Global.IAW.controls.IAWTabPanel

    '''<summary>
    '''IAWLabel5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel5 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''cbSettigsFixed control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbSettigsFixed As Global.IAW.controls.IAWCheckBox

    '''<summary>
    '''IAWLabel34 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel34 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''ddlbBackgroundType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlbBackgroundType As Global.IAW.controls.IAWDropDownList

    '''<summary>
    '''IAWLabel9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel9 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''txtModelbg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtModelbg As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''IAWLabel35 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel35 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''ddlbBackgroundImage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlbBackgroundImage As Global.IAW.controls.IAWDropDownList

    '''<summary>
    '''IAWLabel48 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel48 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''ddlbBackgroundGradient control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlbBackgroundGradient As Global.IAW.controls.IAWDropDownList

    '''<summary>
    '''IAWLabel47 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel47 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''ddlbDirection control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlbDirection As Global.IAW.controls.IAWDropDownList

    '''<summary>
    '''lblRelationshipLinesTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRelationshipLinesTitle As Global.IAW.controls.IAWLabel

    '''<summary>
    '''IAWLabel75 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel75 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''txtlinkColour control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtlinkColour As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''txtLinkHover control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLinkHover As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''IAWLabel32 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel32 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''txtLinkTooltipfg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLinkTooltipfg As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''txtLinkTooltipbg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLinkTooltipbg As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''txtLinkTooltipBorder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLinkTooltipBorder As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''IAWLabel76 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel76 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''numLinkWidth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents numLinkWidth As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''slideLinkWidth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents slideLinkWidth As Global.AjaxControlToolkit.SliderExtender

    '''<summary>
    '''labLinkWidth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents labLinkWidth As Global.IAW.controls.IAWLabel

    '''<summary>
    '''IAWLabel77 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel77 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''ddlbLinkStyle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlbLinkStyle As Global.IAW.controls.IAWDropDownList

    '''<summary>
    '''IAWTabPanel5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWTabPanel5 As Global.IAW.controls.IAWTabPanel

    '''<summary>
    '''IAWLabel2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel2 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''txtNodefg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNodefg As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''txtNodeTxtBg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNodeTxtBg As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''txtNodebg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNodebg As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''txtNodeBorder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNodeBorder As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''cbNodeTxtBlock control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbNodeTxtBlock As Global.IAW.controls.IAWCheckBox

    '''<summary>
    '''IAWLabel31 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel31 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''txtHighlightfg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtHighlightfg As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''txtHighlightbg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtHighlightbg As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''txtHighlightbBorder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtHighlightbBorder As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''IAWLabel72 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel72 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''txtTTfg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTTfg As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''txtTTbg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTTbg As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''txtTTBorder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTTBorder As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''cbShowShadow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbShowShadow As Global.IAW.controls.IAWCheckBox

    '''<summary>
    '''txtShadow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtShadow As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''IAWLabel7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel7 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''txtIconfg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtIconfg As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''txtIconHover control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtIconHover As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''IAWLabel73 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel73 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''rbCornerRectangle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbCornerRectangle As Global.IAW.controls.IAWRadioButton

    '''<summary>
    '''rbCornerRoundedRectangle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbCornerRoundedRectangle As Global.IAW.controls.IAWRadioButton

    '''<summary>
    '''IAWLabel3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel3 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''numMaxNodeWidth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents numMaxNodeWidth As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''slideMaxNodeWidth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents slideMaxNodeWidth As Global.AjaxControlToolkit.SliderExtender

    '''<summary>
    '''labMaxNodeWidth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents labMaxNodeWidth As Global.IAW.controls.IAWLabel

    '''<summary>
    '''IAWLabel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel1 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''numNodeWidth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents numNodeWidth As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''slideNodeWidth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents slideNodeWidth As Global.AjaxControlToolkit.SliderExtender

    '''<summary>
    '''labNodeWidth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents labNodeWidth As Global.IAW.controls.IAWLabel

    '''<summary>
    '''IAWLabel4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel4 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''numMaxNodeHeight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents numMaxNodeHeight As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''slideMaxNodeHeight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents slideMaxNodeHeight As Global.AjaxControlToolkit.SliderExtender

    '''<summary>
    '''labMaxNodeHeight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents labMaxNodeHeight As Global.IAW.controls.IAWLabel

    '''<summary>
    '''IAWLabel19 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel19 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''numNodeHeight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents numNodeHeight As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''slideNodeHeight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents slideNodeHeight As Global.AjaxControlToolkit.SliderExtender

    '''<summary>
    '''labNodeHeight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents labNodeHeight As Global.IAW.controls.IAWLabel

    '''<summary>
    '''IAWTabPanel6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWTabPanel6 As Global.IAW.controls.IAWTabPanel

    '''<summary>
    '''IAWLabel14 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel14 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''IAWLabel15 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel15 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''IAWLabel18 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel18 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''IAWLabel20 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel20 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''IAWLabel21 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel21 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''IAWLabel22 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel22 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''btnGlobalSave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnGlobalSave As Global.IAW.controls.IAWHyperLinkButton

    '''<summary>
    '''btnGlobalCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnGlobalCancel As Global.IAW.controls.IAWHyperLinkButton

    '''<summary>
    '''hdnBrandID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnBrandID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''popBrand control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents popBrand As Global.IAW.controls.IAWPanel

    '''<summary>
    '''helplink_popBrand control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents helplink_popBrand As Global.wuc_help

    '''<summary>
    '''IAWLabel17 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel17 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''txtBrandName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBrandName As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''RequiredFieldValidator99 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RequiredFieldValidator99 As Global.IAW.controls.IAWRequiredFieldValidator

    '''<summary>
    '''cvBrandName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cvBrandName As Global.IAW.controls.IAWCustomValidator

    '''<summary>
    '''IAWLabel30 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel30 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''cbDefaultBrand control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbDefaultBrand As Global.IAW.controls.IAWCheckBox

    '''<summary>
    '''btnBrandSave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnBrandSave As Global.IAW.controls.IAWHyperLinkButton

    '''<summary>
    '''btnBrandCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnBrandCancel As Global.IAW.controls.IAWHyperLinkButton

    '''<summary>
    '''btnBrandFake control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnBrandFake As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''mpeBrandForm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mpeBrandForm As Global.AjaxControlToolkit.ModalPopupExtender

    '''<summary>
    '''popTheme control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents popTheme As Global.IAW.controls.IAWPanel

    '''<summary>
    '''tcTheme control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tcTheme As Global.AjaxControlToolkit.TabContainer

    '''<summary>
    '''tpCopyFromBrands control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tpCopyFromBrands As Global.IAW.controls.IAWTabPanel

    '''<summary>
    '''rblBrand control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblBrand As Global.IAW.controls.IAWRadioButtonList

    '''<summary>
    '''tpCopyFromThemes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tpCopyFromThemes As Global.IAW.controls.IAWTabPanel

    '''<summary>
    '''grdTheme control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdTheme As Global.IAW.controls.IAWGrid

    '''<summary>
    '''IAWLabel44 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel44 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''btnThemeSave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnThemeSave As Global.IAW.controls.IAWHyperLinkButton

    '''<summary>
    '''btnThemeCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnThemeCancel As Global.IAW.controls.IAWHyperLinkButton

    '''<summary>
    '''btnThemeFake control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnThemeFake As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''mpeThemeForm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mpeThemeForm As Global.AjaxControlToolkit.ModalPopupExtender

    '''<summary>
    '''hdnClientUnique control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnClientUnique As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''popBackground control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents popBackground As Global.IAW.controls.IAWPanel

    '''<summary>
    '''IAWLabel24 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel24 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''rbBgSelectGradient control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbBgSelectGradient As Global.IAW.controls.IAWRadioButton

    '''<summary>
    '''rbBgSelectImage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbBgSelectImage As Global.IAW.controls.IAWRadioButton

    '''<summary>
    '''IAWLabel27 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel27 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''txtBgName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBgName As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''RequiredFieldValidator2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RequiredFieldValidator2 As Global.IAW.controls.IAWRequiredFieldValidator

    '''<summary>
    '''cvBgName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cvBgName As Global.IAW.controls.IAWCustomValidator

    '''<summary>
    '''divBgGradient control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divBgGradient As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''IAWLabel25 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel25 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''btnAddNewColour control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddNewColour As Global.IAW.controls.IAWHyperLinkButton

    '''<summary>
    '''rbLinearGradient control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbLinearGradient As Global.IAW.controls.IAWRadioButton

    '''<summary>
    '''rbRadialGradient control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbRadialGradient As Global.IAW.controls.IAWRadioButton

    '''<summary>
    '''divBgImage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divBgImage As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''IAWLabel29 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel29 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''ddlbImageRepeatType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlbImageRepeatType As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnBgImageSelector control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnBgImageSelector As Global.IAW.controls.IAWHyperLinkButton

    '''<summary>
    '''bgImageLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bgImageLabel As Global.IAW.controls.IAWLabel

    '''<summary>
    '''FileUpload2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FileUpload2 As Global.System.Web.UI.WebControls.FileUpload

    '''<summary>
    '''btnBackgroundSave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnBackgroundSave As Global.IAW.controls.IAWHyperLinkButton

    '''<summary>
    '''btnBackgroundCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnBackgroundCancel As Global.IAW.controls.IAWHyperLinkButton

    '''<summary>
    '''btnBackgroundFake control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnBackgroundFake As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''mpeBackgroundForm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mpeBackgroundForm As Global.AjaxControlToolkit.ModalPopupExtender

    '''<summary>
    '''popDelete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents popDelete As Global.IAW.controls.IAWPanel

    '''<summary>
    '''lblDeleteConfirm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDeleteConfirm As Global.IAW.controls.IAWLabel

    '''<summary>
    '''btnDeleteOk control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDeleteOk As Global.IAW.controls.IAWHyperLinkButton

    '''<summary>
    '''btnDeleteCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDeleteCancel As Global.IAW.controls.IAWHyperLinkButton

    '''<summary>
    '''btnDeleteFake control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDeleteFake As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''mpeDelete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mpeDelete As Global.AjaxControlToolkit.ModalPopupExtender

    '''<summary>
    '''popBrandDelete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents popBrandDelete As Global.IAW.controls.IAWPanel

    '''<summary>
    '''IAWLabel26 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel26 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''btnBrandDeleteOk control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnBrandDeleteOk As Global.IAW.controls.IAWHyperLinkButton

    '''<summary>
    '''btnBrandDeleteCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnBrandDeleteCancel As Global.IAW.controls.IAWHyperLinkButton

    '''<summary>
    '''btnBrandDeleteFake control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnBrandDeleteFake As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''mpeBrandDelete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mpeBrandDelete As Global.AjaxControlToolkit.ModalPopupExtender

    '''<summary>
    '''popSimplifiedWarning control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents popSimplifiedWarning As Global.IAW.controls.IAWPanel

    '''<summary>
    '''IAWLabel46 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel46 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''btnSimplifiedWarningOk control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSimplifiedWarningOk As Global.IAW.controls.IAWHyperLinkButton

    '''<summary>
    '''btnSimplifiedWarningCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSimplifiedWarningCancel As Global.IAW.controls.IAWHyperLinkButton

    '''<summary>
    '''btnSimplifiedWarningFake control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSimplifiedWarningFake As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''mpeSimplifiedWarning control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mpeSimplifiedWarning As Global.AjaxControlToolkit.ModalPopupExtender
End Class
