'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class client_users

    '''<summary>
    '''pnlUsers control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlUsers As Global.IAW.controls.IAWPanel

    '''<summary>
    '''grdUsers control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdUsers As Global.IAW.controls.IAWGrid

    '''<summary>
    '''hdnUserRef control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnUserRef As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''popUser control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents popUser As Global.IAW.controls.IAWPanel

    '''<summary>
    '''helplink_popUser control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents helplink_popUser As Global.wuc_help

    '''<summary>
    '''hdnURL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnURL As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''IAWLabel48 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel48 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''txtForename control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtForename As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''rfvForename control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvForename As Global.IAW.controls.IAWRequiredFieldValidator

    '''<summary>
    '''IAWLabel2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel2 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''txtSurname control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSurname As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''rfvSurname control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvSurname As Global.IAW.controls.IAWRequiredFieldValidator

    '''<summary>
    '''IAWLabel3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel3 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''txtEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEmail As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''rfvEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvEmail As Global.IAW.controls.IAWRequiredFieldValidator

    '''<summary>
    '''cvEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cvEmail As Global.IAW.controls.IAWCustomValidator

    '''<summary>
    '''cvEmailDomain control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cvEmailDomain As Global.IAW.controls.IAWCustomValidator

    '''<summary>
    '''IAWLabel4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel4 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''ddlbRole control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlbRole As Global.IAW.controls.IAWDropDownList

    '''<summary>
    '''IAWLabel5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel5 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''ddlbLanguage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlbLanguage As Global.IAW.controls.IAWDropDownList

    '''<summary>
    '''IAWLabel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel1 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''ddlbBrand control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlbBrand As Global.IAW.controls.IAWDropDownList

    '''<summary>
    '''IAWLabel6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel6 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''cbActive control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbActive As Global.IAW.controls.IAWCheckBox

    '''<summary>
    '''btnCopyLoginURL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCopyLoginURL As Global.IAW.controls.IAWHyperLinkButton

    '''<summary>
    '''labInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents labInfo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnUserSave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnUserSave As Global.IAW.controls.IAWHyperLinkButton

    '''<summary>
    '''btnUserCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnUserCancel As Global.IAW.controls.IAWHyperLinkButton

    '''<summary>
    '''txtErrorMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtErrorMessage As Global.IAW.controls.IAWLabel

    '''<summary>
    '''btnUserFake control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnUserFake As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''mpeUserForm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mpeUserForm As Global.AjaxControlToolkit.ModalPopupExtender

    '''<summary>
    '''popDelete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents popDelete As Global.IAW.controls.IAWPanel

    '''<summary>
    '''lblDeleteConfirm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDeleteConfirm As Global.IAW.controls.IAWLabel

    '''<summary>
    '''btnDeleteOk control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDeleteOk As Global.IAW.controls.IAWHyperLinkButton

    '''<summary>
    '''btnDeleteCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDeleteCancel As Global.IAW.controls.IAWHyperLinkButton

    '''<summary>
    '''btnDeleteFake control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDeleteFake As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''mpeDelete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mpeDelete As Global.AjaxControlToolkit.ModalPopupExtender
End Class
