'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class datasources

    '''<summary>
    '''panel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panel1 As Global.IAW.controls.IAWPanel

    '''<summary>
    '''helplink_datasource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents helplink_datasource As Global.wuc_help

    '''<summary>
    '''grdDatasource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdDatasource As Global.IAW.controls.IAWGrid

    '''<summary>
    '''lblDataSourceMsg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDataSourceMsg As Global.IAW.controls.IAWLabel

    '''<summary>
    '''pnlDataSourceDetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlDataSourceDetails As Global.IAW.controls.IAWPanel

    '''<summary>
    '''TabContainer1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TabContainer1 As Global.AjaxControlToolkit.TabContainer

    '''<summary>
    '''tpFields control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tpFields As Global.IAW.controls.IAWTabPanel

    '''<summary>
    '''trActionButtons control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trActionButtons As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''btnFieldsAccept control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnFieldsAccept As Global.IAW.controls.IAWHyperLinkButton

    '''<summary>
    '''btnFieldsReject control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnFieldsReject As Global.IAW.controls.IAWHyperLinkButton

    '''<summary>
    '''grdDates control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdDates As Global.IAW.controls.IAWGrid

    '''<summary>
    '''grdFieldList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdFieldList As Global.IAW.controls.IAWGrid

    '''<summary>
    '''tpAccessControl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tpAccessControl As Global.IAW.controls.IAWTabPanel

    '''<summary>
    '''grdDataSourceAccess control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdDataSourceAccess As Global.IAW.controls.IAWGrid

    '''<summary>
    '''hdnDataSourceID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnDataSourceID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''popDataSource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents popDataSource As Global.IAW.controls.IAWPanel

    '''<summary>
    '''helplink_popDataSource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents helplink_popDataSource As Global.wuc_help

    '''<summary>
    '''IAWLabel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel1 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''txtShortRef control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtShortRef As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''RequiredFieldValidator6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RequiredFieldValidator6 As Global.IAW.controls.IAWRequiredFieldValidator

    '''<summary>
    '''IAWLabel10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel10 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''txtZipPassword control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtZipPassword As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''IAWLabel30 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel30 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''cbPhotosApplicable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbPhotosApplicable As Global.IAW.controls.IAWCheckBox

    '''<summary>
    '''btnDataSourceSave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDataSourceSave As Global.IAW.controls.IAWHyperLinkButton

    '''<summary>
    '''btnDataSourceCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDataSourceCancel As Global.IAW.controls.IAWHyperLinkButton

    '''<summary>
    '''btnDataSourceFake control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDataSourceFake As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''mpeDataSourceForm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mpeDataSourceForm As Global.AjaxControlToolkit.ModalPopupExtender

    '''<summary>
    '''hdnIdx control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnIdx As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''popField control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents popField As Global.IAW.controls.IAWPanel

    '''<summary>
    '''helplink_popField control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents helplink_popField As Global.wuc_help

    '''<summary>
    '''IAWLabel2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel2 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''lblFieldNum control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFieldNum As Global.IAW.controls.IAWLabel

    '''<summary>
    '''IAWLabel8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel8 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''txtFieldName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFieldName As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''IAWLabel9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel9 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''ddlbFieldType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlbFieldType As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''trFieldLength control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trFieldLength As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''lblFieldLength control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFieldLength As Global.IAW.controls.IAWLabel

    '''<summary>
    '''txtFieldLength control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFieldLength As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''ftbeFieldLength control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ftbeFieldLength As Global.AjaxControlToolkit.FilteredTextBoxExtender

    '''<summary>
    '''rvFieldLength control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rvFieldLength As Global.IAW.controls.IAWRangeValidator

    '''<summary>
    '''trFieldFormat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trFieldFormat As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''IAWLabel6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel6 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''ddlbFieldFormat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlbFieldFormat As Global.IAW.controls.IAWDropDownList

    '''<summary>
    '''trItemRefField control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trItemRefField As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''IAWLabel11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel11 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''cbUniqueRef control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbUniqueRef As Global.IAW.controls.IAWCheckBox

    '''<summary>
    '''trParentRefField control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trParentRefField As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''IAWLabel7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel7 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''cbParentRefField control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbParentRefField As Global.IAW.controls.IAWCheckBox

    '''<summary>
    '''btnFieldSave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnFieldSave As Global.IAW.controls.IAWHyperLinkButton

    '''<summary>
    '''btnFieldCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnFieldCancel As Global.IAW.controls.IAWHyperLinkButton

    '''<summary>
    '''btnFieldFake control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnFieldFake As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''mpeFieldForm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mpeFieldForm As Global.AjaxControlToolkit.ModalPopupExtender

    '''<summary>
    '''popReject control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents popReject As Global.IAW.controls.IAWPanel

    '''<summary>
    '''IAWLabel12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel12 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''lblRejectDataSource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRejectDataSource As Global.IAW.controls.IAWLabel

    '''<summary>
    '''IAWLabel13 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel13 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''lblRejectUploadDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRejectUploadDate As Global.IAW.controls.IAWLabel

    '''<summary>
    '''IAWLabel14 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel14 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''lblRejectUploadedBy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRejectUploadedBy As Global.IAW.controls.IAWLabel

    '''<summary>
    '''IAWLabel15 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel15 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''txtRejectReason control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRejectReason As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''rfvRejectReason control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvRejectReason As Global.IAW.controls.IAWRequiredFieldValidator

    '''<summary>
    '''btnRejectProceed control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnRejectProceed As Global.IAW.controls.IAWHyperLinkButton

    '''<summary>
    '''btnRejectCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnRejectCancel As Global.IAW.controls.IAWHyperLinkButton

    '''<summary>
    '''btnRejectFake control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnRejectFake As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''mpeRejectForm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mpeRejectForm As Global.AjaxControlToolkit.ModalPopupExtender

    '''<summary>
    '''hdnDataSourceAccessID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnDataSourceAccessID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''popDataSourceAccess control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents popDataSourceAccess As Global.IAW.controls.IAWPanel

    '''<summary>
    '''helplink_popDataSourceAccess control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents helplink_popDataSourceAccess As Global.wuc_help

    '''<summary>
    '''IAWLabel3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel3 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''ddlbAccessType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlbAccessType As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''trRoles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trRoles As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''IAWLabel5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel5 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''ddlbAccessRole control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlbAccessRole As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''trSearchUser control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trSearchUser As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''IAWLabel4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel4 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''txtSearchUser control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSearchUser As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''fteSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fteSearch As Global.AjaxControlToolkit.FilteredTextBoxExtender

    '''<summary>
    '''btnSearchUser control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSearchUser As Global.IAW.controls.IAWHyperLinkButton

    '''<summary>
    '''lblUserExists control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUserExists As Global.IAW.controls.IAWLabel

    '''<summary>
    '''pnlUserList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlUserList As Global.IAW.controls.IAWPanel

    '''<summary>
    '''grdSearchUser control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdSearchUser As Global.IAW.controls.IAWGrid

    '''<summary>
    '''btnDataSourceAccessSave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDataSourceAccessSave As Global.IAW.controls.IAWHyperLinkButton

    '''<summary>
    '''btnDataSourceAccessCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDataSourceAccessCancel As Global.IAW.controls.IAWHyperLinkButton

    '''<summary>
    '''btnDataSourceAccessFake control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDataSourceAccessFake As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''mpeDataSourceAccessForm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mpeDataSourceAccessForm As Global.AjaxControlToolkit.ModalPopupExtender

    '''<summary>
    '''popDelete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents popDelete As Global.IAW.controls.IAWPanel

    '''<summary>
    '''lblDeleteConfirm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDeleteConfirm As Global.IAW.controls.IAWLabel

    '''<summary>
    '''btnDeleteOk control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDeleteOk As Global.IAW.controls.IAWHyperLinkButton

    '''<summary>
    '''btnDeleteCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDeleteCancel As Global.IAW.controls.IAWHyperLinkButton

    '''<summary>
    '''popIgnorePrimary control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents popIgnorePrimary As Global.IAW.controls.IAWPanel

    '''<summary>
    '''helplink_popIgnorePrimary control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents helplink_popIgnorePrimary As Global.wuc_help

    '''<summary>
    '''lblIgnore control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblIgnore As Global.IAW.controls.IAWLabel

    '''<summary>
    '''btnIgnorePrimarySave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnIgnorePrimarySave As Global.IAW.controls.IAWHyperLinkButton

    '''<summary>
    '''btnIgnorePrimaryCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnIgnorePrimaryCancel As Global.IAW.controls.IAWHyperLinkButton

    '''<summary>
    '''btnIgnorePrimaryFake control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnIgnorePrimaryFake As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''mpeIgnorePrimaryForm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mpeIgnorePrimaryForm As Global.AjaxControlToolkit.ModalPopupExtender
End Class
