'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class dataviews

    '''<summary>
    '''pnlDataSource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlDataSource As Global.IAW.controls.IAWPanel

    '''<summary>
    '''grdDatasource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdDatasource As Global.IAW.controls.IAWGrid

    '''<summary>
    '''pnlDataView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlDataView As Global.IAW.controls.IAWPanel

    '''<summary>
    '''grdDataView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdDataView As Global.IAW.controls.IAWGrid

    '''<summary>
    '''lblDataViewMsg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDataViewMsg As Global.IAW.controls.IAWLabel

    '''<summary>
    '''pnlDisplay control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlDisplay As Global.IAW.controls.IAWPanel

    '''<summary>
    '''hdnDrop control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnDrop As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''btnDrop control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDrop As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''divAccButtons control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divAccButtons As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''btnAccSave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAccSave As Global.IAW.controls.IAWHyperLinkButton

    '''<summary>
    '''btnAccCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAccCancel As Global.IAW.controls.IAWHyperLinkButton

    '''<summary>
    '''grdFields control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdFields As Global.IAW.controls.IAWGrid

    '''<summary>
    '''hdnAccValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnAccValue As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''btnAccPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAccPanel As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''accPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents accPanel As Global.AjaxControlToolkit.Accordion

    '''<summary>
    '''accPanelOCA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents accPanelOCA As Global.AjaxControlToolkit.AccordionPane

    '''<summary>
    '''grdDispOCA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdDispOCA As Global.IAW.controls.IAWGrid

    '''<summary>
    '''accPanelCoParent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents accPanelCoParent As Global.AjaxControlToolkit.AccordionPane

    '''<summary>
    '''grdCoParent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdCoParent As Global.IAW.controls.IAWGrid

    '''<summary>
    '''accPanelAEAHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents accPanelAEAHeader As Global.AjaxControlToolkit.AccordionPane

    '''<summary>
    '''btnAEAHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAEAHeader As Global.IAW.controls.IAWHyperLinkButton

    '''<summary>
    '''grdAEAHead control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdAEAHead As Global.IAW.controls.IAWGrid

    '''<summary>
    '''accPanelAEAFields control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents accPanelAEAFields As Global.AjaxControlToolkit.AccordionPane

    '''<summary>
    '''grdAEAFields control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdAEAFields As Global.IAW.controls.IAWGrid

    '''<summary>
    '''accPanelAEASort control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents accPanelAEASort As Global.AjaxControlToolkit.AccordionPane

    '''<summary>
    '''grdAEASort control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdAEASort As Global.IAW.controls.IAWGrid

    '''<summary>
    '''accPanelFormDisplay control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents accPanelFormDisplay As Global.AjaxControlToolkit.AccordionPane

    '''<summary>
    '''btnFormDispRow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnFormDispRow As Global.IAW.controls.IAWHyperLinkButton

    '''<summary>
    '''btnFormDispCol control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnFormDispCol As Global.IAW.controls.IAWHyperLinkButton

    '''<summary>
    '''grdFormDisplay control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdFormDisplay As Global.IAW.controls.IAWGrid

    '''<summary>
    '''accPanelListHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents accPanelListHeader As Global.AjaxControlToolkit.AccordionPane

    '''<summary>
    '''btnListHead control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnListHead As Global.IAW.controls.IAWHyperLinkButton

    '''<summary>
    '''grdListHeaders control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdListHeaders As Global.IAW.controls.IAWGrid

    '''<summary>
    '''accPanelListData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents accPanelListData As Global.AjaxControlToolkit.AccordionPane

    '''<summary>
    '''grdListData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdListData As Global.IAW.controls.IAWGrid

    '''<summary>
    '''accPanelListSort control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents accPanelListSort As Global.AjaxControlToolkit.AccordionPane

    '''<summary>
    '''grdListSort control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdListSort As Global.IAW.controls.IAWGrid

    '''<summary>
    '''hdnViewID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnViewID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''popDataView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents popDataView As Global.IAW.controls.IAWPanel

    '''<summary>
    '''helplink_popDataView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents helplink_popDataView As Global.wuc_help

    '''<summary>
    '''tcMainContainer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tcMainContainer As Global.AjaxControlToolkit.TabContainer

    '''<summary>
    '''tpGeneral control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tpGeneral As Global.IAW.controls.IAWTabPanel

    '''<summary>
    '''IAWLabel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel1 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''ddlbDataSource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlbDataSource As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''IAWLabel3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel3 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''ddlbOccurrenceDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlbOccurrenceDate As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''IAWLabel2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel2 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''txtReference control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtReference As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''RequiredFieldValidator2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RequiredFieldValidator2 As Global.IAW.controls.IAWRequiredFieldValidator

    '''<summary>
    '''trTxtAEA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trTxtAEA As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''IAWLabel10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel10 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''txtAEA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAEA As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''RequiredFieldValidator1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RequiredFieldValidator1 As Global.IAW.controls.IAWRequiredFieldValidator

    '''<summary>
    '''trShowDetailsType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trShowDetailsType As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''IAWLabel32 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel32 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''ddlbShowDetailsType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlbShowDetailsType As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''trLinkedDataSource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trLinkedDataSource As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''IAWLabel45 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel45 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''ddlbDetailsDataSource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlbDetailsDataSource As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''trDetailFieldFrom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trDetailFieldFrom As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''IAWLabel46 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel46 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''ddlbDetailFieldFrom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlbDetailFieldFrom As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''trDetailFieldTo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trDetailFieldTo As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''IAWLabel47 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel47 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''ddlbDetailFieldTo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlbDetailFieldTo As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''trAllowDrilldown control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trAllowDrilldown As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''IAWLabel7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel7 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''cbAllowDrilldown control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbAllowDrilldown As Global.IAW.controls.IAWCheckBox

    '''<summary>
    '''IAWLabel24 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel24 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''tpChart control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tpChart As Global.IAW.controls.IAWTabPanel

    '''<summary>
    '''hdnAttrib control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnAttrib As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''ddlbFont control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlbFont As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''IAWLabel14 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel14 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''cbSettigsFixed control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbSettigsFixed As Global.IAW.controls.IAWCheckBox

    '''<summary>
    '''IAWLabel34 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel34 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''ddlbBackgroundType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlbBackgroundType As Global.IAW.controls.IAWDropDownList

    '''<summary>
    '''IAWLabel9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel9 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''txtModelbg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtModelbg As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''IAWLabel35 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel35 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''ddlbBackgroundImage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlbBackgroundImage As Global.IAW.controls.IAWDropDownList

    '''<summary>
    '''IAWLabel4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel4 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''ddlbBackgroundGradient control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlbBackgroundGradient As Global.IAW.controls.IAWDropDownList

    '''<summary>
    '''IAWLabel5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel5 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''ddlbDirection control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlbDirection As Global.IAW.controls.IAWDropDownList

    '''<summary>
    '''trPhotosApplicable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trPhotosApplicable As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''cbPhotosApplicable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbPhotosApplicable As Global.IAW.controls.IAWCheckBox

    '''<summary>
    '''ddlbImagePosition control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlbImagePosition As Global.IAW.controls.IAWDropDownList

    '''<summary>
    '''lblRelationshipLinesTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRelationshipLinesTitle As Global.IAW.controls.IAWLabel

    '''<summary>
    '''IAWLabel75 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel75 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''txtlinkColour control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtlinkColour As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''txtLinkHover control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLinkHover As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''IAWLabel13 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel13 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''txtLinkTooltipfg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLinkTooltipfg As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''txtLinkTooltipbg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLinkTooltipbg As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''txtLinkTooltipBorder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLinkTooltipBorder As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''IAWLabel76 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel76 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''numLinkWidth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents numLinkWidth As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''slideLinkWidth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents slideLinkWidth As Global.AjaxControlToolkit.SliderExtender

    '''<summary>
    '''labLinkWidth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents labLinkWidth As Global.IAW.controls.IAWLabel

    '''<summary>
    '''IAWLabel77 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel77 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''ddlbLinkStyle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlbLinkStyle As Global.IAW.controls.IAWDropDownList

    '''<summary>
    '''tpNodes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tpNodes As Global.IAW.controls.IAWTabPanel

    '''<summary>
    '''IAWLabel16 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel16 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''txtNodefg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNodefg As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''txtNodeTxtBg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNodeTxtBg As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''txtNodebg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNodebg As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''txtNodeBorder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNodeBorder As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''cbNodeTxtBlock control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbNodeTxtBlock As Global.IAW.controls.IAWCheckBox

    '''<summary>
    '''IAWLabel31 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel31 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''txtHighlightfg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtHighlightfg As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''txtHighlightbg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtHighlightbg As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''txtHighlightbBorder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtHighlightbBorder As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''IAWLabel72 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel72 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''txtTTfg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTTfg As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''txtTTbg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTTbg As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''txtTTBorder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTTBorder As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''cbShowShadow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbShowShadow As Global.IAW.controls.IAWCheckBox

    '''<summary>
    '''txtShadow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtShadow As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''IAWLabel33 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel33 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''txtIconfg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtIconfg As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''txtIconHover control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtIconHover As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''IAWLabel73 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel73 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''rbCornerRectangle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbCornerRectangle As Global.IAW.controls.IAWRadioButton

    '''<summary>
    '''rbCornerRoundedRectangle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbCornerRoundedRectangle As Global.IAW.controls.IAWRadioButton

    '''<summary>
    '''IAWLabel8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel8 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''numMaxNodeWidth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents numMaxNodeWidth As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''slideMaxNodeWidth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents slideMaxNodeWidth As Global.AjaxControlToolkit.SliderExtender

    '''<summary>
    '''labMaxNodeWidth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents labMaxNodeWidth As Global.IAW.controls.IAWLabel

    '''<summary>
    '''IAWLabel11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel11 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''numNodeWidth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents numNodeWidth As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''slideNodeWidth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents slideNodeWidth As Global.AjaxControlToolkit.SliderExtender

    '''<summary>
    '''labNodeWidth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents labNodeWidth As Global.IAW.controls.IAWLabel

    '''<summary>
    '''IAWLabel12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel12 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''numMaxNodeHeight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents numMaxNodeHeight As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''slideMaxNodeHeight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents slideMaxNodeHeight As Global.AjaxControlToolkit.SliderExtender

    '''<summary>
    '''labMaxNodeHeight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents labMaxNodeHeight As Global.IAW.controls.IAWLabel

    '''<summary>
    '''IAWLabel19 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel19 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''numNodeHeight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents numNodeHeight As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''slideNodeHeight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents slideNodeHeight As Global.AjaxControlToolkit.SliderExtender

    '''<summary>
    '''labNodeHeight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents labNodeHeight As Global.IAW.controls.IAWLabel

    '''<summary>
    '''tpFont control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tpFont As Global.IAW.controls.IAWTabPanel

    '''<summary>
    '''IAWLabel17 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel17 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''IAWLabel18 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel18 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''IAWLabel20 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel20 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''IAWLabel21 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel21 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''IAWLabel22 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel22 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''IAWLabel23 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel23 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''btnDataViewSave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDataViewSave As Global.IAW.controls.IAWHyperLinkButton

    '''<summary>
    '''btnDataViewCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDataViewCancel As Global.IAW.controls.IAWHyperLinkButton

    '''<summary>
    '''btnDataViewFake control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDataViewFake As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''mpeDataViewForm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mpeDataViewForm As Global.AjaxControlToolkit.ModalPopupExtender

    '''<summary>
    '''hdnDispKey control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnDispKey As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdnFieldType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnFieldType As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''popDisplayEntry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents popDisplayEntry As Global.IAW.controls.IAWPanel

    '''<summary>
    '''helplink_popDisplayEntry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents helplink_popDisplayEntry As Global.wuc_help

    '''<summary>
    '''trDEtext control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trDEtext As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''IAWLabel48 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel48 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''txtDEtext control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDEtext As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''trDEtextHover control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trDEtextHover As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''lblDEtextHover control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDEtextHover As Global.IAW.controls.IAWLabel

    '''<summary>
    '''trDECase control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trDECase As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''IAWLabel6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel6 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''cbDEUpper control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbDEUpper As Global.IAW.controls.IAWCheckBox

    '''<summary>
    '''cbDELower control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbDELower As Global.IAW.controls.IAWCheckBox

    '''<summary>
    '''cbDECapitalise control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbDECapitalise As Global.IAW.controls.IAWCheckBox

    '''<summary>
    '''trDEPart control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trDEPart As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''IAWLabel15 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel15 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''cbDEPartLeft control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbDEPartLeft As Global.IAW.controls.IAWCheckBox

    '''<summary>
    '''cbDEPartMid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbDEPartMid As Global.IAW.controls.IAWCheckBox

    '''<summary>
    '''cbDEPartRight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbDEPartRight As Global.IAW.controls.IAWCheckBox

    '''<summary>
    '''pnlDEStart control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlDEStart As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblDEStart control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDEStart As Global.IAW.controls.IAWLabel

    '''<summary>
    '''txtDEStart control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDEStart As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''fteDEStart control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fteDEStart As Global.AjaxControlToolkit.FilteredTextBoxExtender

    '''<summary>
    '''pnlDELength control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlDELength As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblDELength control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDELength As Global.IAW.controls.IAWLabel

    '''<summary>
    '''txtDELength control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDELength As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''fteDELength control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fteDELength As Global.AjaxControlToolkit.FilteredTextBoxExtender

    '''<summary>
    '''trDEDateFormat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trDEDateFormat As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''IAWLabel29 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel29 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''ddlbDEDateFormat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlbDEDateFormat As Global.IAW.controls.IAWDropDownList

    '''<summary>
    '''trDEcurrency control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trDEcurrency As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''IAWLabel25 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel25 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''cbDEcurrency control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbDEcurrency As Global.IAW.controls.IAWCheckBox

    '''<summary>
    '''trDEdecs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trDEdecs As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''IAWLabel26 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel26 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''txtDEdecs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDEdecs As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''FilteredTextBoxExtender1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FilteredTextBoxExtender1 As Global.AjaxControlToolkit.FilteredTextBoxExtender

    '''<summary>
    '''trDEgroup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trDEgroup As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''IAWLabel27 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel27 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''cbDEgroup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbDEgroup As Global.IAW.controls.IAWCheckBox

    '''<summary>
    '''trDEbool control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trDEbool As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''IAWLabel28 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel28 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''ddlbDEbool control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlbDEbool As Global.IAW.controls.IAWDropDownList

    '''<summary>
    '''btnDisplayEntrySave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDisplayEntrySave As Global.IAW.controls.IAWHyperLinkButton

    '''<summary>
    '''btnDisplayEntryCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDisplayEntryCancel As Global.IAW.controls.IAWHyperLinkButton

    '''<summary>
    '''btnDisplayEntryFake control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDisplayEntryFake As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''mpeDisplayEntryForm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mpeDisplayEntryForm As Global.AjaxControlToolkit.ModalPopupExtender

    '''<summary>
    '''popMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents popMessage As Global.IAW.controls.IAWPanel

    '''<summary>
    '''lblMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMessage As Global.IAW.controls.IAWLabel

    '''<summary>
    '''btnMessageOk control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnMessageOk As Global.IAW.controls.IAWHyperLinkButton

    '''<summary>
    '''btnMessageFake control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnMessageFake As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''mpeMessageForm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mpeMessageForm As Global.AjaxControlToolkit.ModalPopupExtender

    '''<summary>
    '''popDelete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents popDelete As Global.IAW.controls.IAWPanel

    '''<summary>
    '''lblDeleteConfirm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDeleteConfirm As Global.IAW.controls.IAWLabel

    '''<summary>
    '''btnDeleteOk control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDeleteOk As Global.IAW.controls.IAWHyperLinkButton

    '''<summary>
    '''btnDeleteCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDeleteCancel As Global.IAW.controls.IAWHyperLinkButton
End Class
