'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ModelList

    '''<summary>
    '''ErrorPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ErrorPanel As Global.IAW.controls.IAWPanel

    '''<summary>
    '''msg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents msg As Global.IAW.controls.IawMessage

    '''<summary>
    '''Panel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel1 As Global.IAW.controls.IAWPanel

    '''<summary>
    '''cbOptions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbOptions As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''cbPrevious control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbPrevious As Global.IAW.controls.IAWCheckBox

    '''<summary>
    '''cbCurrent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbCurrent As Global.IAW.controls.IAWCheckBox

    '''<summary>
    '''cbFuture control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbFuture As Global.IAW.controls.IAWCheckBox

    '''<summary>
    '''cbOtherUsers control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbOtherUsers As Global.IAW.controls.IAWCheckBox

    '''<summary>
    '''cbPublishedOnly control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbPublishedOnly As Global.IAW.controls.IAWCheckBox

    '''<summary>
    '''grdModels control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdModels As Global.IAW.controls.IAWGrid

    '''<summary>
    '''lblmodelMsg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblmodelMsg As Global.IAW.controls.IAWLabel

    '''<summary>
    '''hdnModelID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnModelID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''popModel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents popModel As Global.IAW.controls.IAWPanel

    '''<summary>
    '''helplink_models control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents helplink_models As Global.wuc_help

    '''<summary>
    '''IAWLabel10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel10 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''ddlbView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlbView As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''trReference control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trReference As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''IAWLabel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel1 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''ddlbReference control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlbReference As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtReference control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtReference As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''IAWRequiredFieldValidator1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWRequiredFieldValidator1 As Global.IAW.controls.IAWRequiredFieldValidator

    '''<summary>
    '''btnRefAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnRefAdd As Global.IAW.controls.IAWImageButton

    '''<summary>
    '''btnRefCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnRefCancel As Global.IAW.controls.IAWImageButton

    '''<summary>
    '''IAWLabel11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel11 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''dtEffectiveDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dtEffectiveDate As Global.IAW.controls.DateDropDown

    '''<summary>
    '''rfvEffectiveDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvEffectiveDate As Global.IAW.controls.IAWRequiredFieldValidator

    '''<summary>
    '''cvEffectiveDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cvEffectiveDate As Global.IAW.controls.IAWCustomValidator

    '''<summary>
    '''trShowImages control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trShowImages As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''IAWLabel7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel7 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''cbShowPhotos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbShowPhotos As Global.IAW.controls.IAWCheckBox

    '''<summary>
    '''trPublished control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trPublished As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''IAWLabel12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel12 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''cbPublished control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbPublished As Global.IAW.controls.IAWCheckBox

    '''<summary>
    '''btnSettingsSave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSettingsSave As Global.IAW.controls.IAWHyperLinkButton

    '''<summary>
    '''btnSettingsCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSettingsCancel As Global.IAW.controls.IAWHyperLinkButton

    '''<summary>
    '''btnModelsFake control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnModelsFake As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''mpeModels control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mpeModels As Global.AjaxControlToolkit.ModalPopupExtender

    '''<summary>
    '''popDelete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents popDelete As Global.IAW.controls.IAWPanel

    '''<summary>
    '''lblDeleteConfirm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDeleteConfirm As Global.IAW.controls.IAWLabel

    '''<summary>
    '''btnDeleteOk control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDeleteOk As Global.IAW.controls.IAWHyperLinkButton

    '''<summary>
    '''btnDeleteCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDeleteCancel As Global.IAW.controls.IAWHyperLinkButton
End Class
