'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class RecoverPassword

    '''<summary>
    '''UPD_panel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UPD_panel As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''btnLogon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnLogon As Global.IAW.controls.IAWHyperLink

    '''<summary>
    '''btnReset control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnReset As Global.IAW.controls.IAWHyperLinkButton

    '''<summary>
    '''lblFieldset control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFieldset As Global.IAW.controls.IAWLabel

    '''<summary>
    '''MainPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MainPanel As Global.IAW.controls.IAWPanel

    '''<summary>
    '''lblMsg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMsg As Global.IAW.controls.IAWLabel

    '''<summary>
    '''lblUserName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUserName As Global.IAW.controls.IAWLabel

    '''<summary>
    '''txtUserName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtUserName As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''RFV_txtUserName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RFV_txtUserName As Global.IAW.controls.IAWRequiredFieldValidator

    '''<summary>
    '''TR_1_sep control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TR_1_sep As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''TR_1_continue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TR_1_continue As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''btn_1_continue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_1_continue As Global.IAW.controls.IAWHyperLinkButton

    '''<summary>
    '''btn_1_hidden control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_1_hidden As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''TR_2_sep1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TR_2_sep1 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''TR_2_qu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TR_2_qu As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''lblSecurityQu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSecurityQu As Global.IAW.controls.IAWLabel

    '''<summary>
    '''txtSecurityQu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSecurityQu As Global.IAW.controls.IAWLabel

    '''<summary>
    '''TR_2_ans control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TR_2_ans As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''lblSecurityAnswer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSecurityAnswer As Global.IAW.controls.IAWLabel

    '''<summary>
    '''txtSecurityAnswer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSecurityAnswer As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''RFV_txtSecurityAnswer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RFV_txtSecurityAnswer As Global.IAW.controls.IAWRequiredFieldValidator

    '''<summary>
    '''TR_2_sep2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TR_2_sep2 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''TR_2_Address control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TR_2_Address As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''IAWLabel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel1 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''rblAddresses control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblAddresses As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''TR_2_sep3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TR_2_sep3 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''TR_2_Continue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TR_2_Continue As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''btn_2_continue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_2_continue As Global.IAW.controls.IAWHyperLinkButton

    '''<summary>
    '''btn_2_hidden control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_2_hidden As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''TR_3_MsgSent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TR_3_MsgSent As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''lab_3_MsgSent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lab_3_MsgSent As Global.IAW.controls.IAWLabel

    '''<summary>
    '''TR_3_sep1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TR_3_sep1 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''TR_3_SecurityCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TR_3_SecurityCode As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''IAWLabel2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel2 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''txtSecurityCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSecurityCode As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''RFV_txtSecurityCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RFV_txtSecurityCode As Global.IAW.controls.IAWRequiredFieldValidator

    '''<summary>
    '''TR_3_labCodeFail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TR_3_labCodeFail As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''labCodeFail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents labCodeFail As Global.IAW.controls.IAWLabel

    '''<summary>
    '''TR_3_sep2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TR_3_sep2 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''TR_3_continue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TR_3_continue As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''btn_3_continue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_3_continue As Global.IAW.controls.IAWHyperLinkButton

    '''<summary>
    '''btn_3_hidden control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_3_hidden As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''TR_4_MsgSent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TR_4_MsgSent As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''lab_4_MsgSent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lab_4_MsgSent As Global.IAW.controls.IAWLabel

    '''<summary>
    '''TR_4_sep1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TR_4_sep1 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''TR_4_ChangePwd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TR_4_ChangePwd As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''ChangePwd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ChangePwd As Global.ChangePassword

    '''<summary>
    '''TR_4_sep2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TR_4_sep2 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''TR_4_continue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TR_4_continue As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''btn_4_continue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_4_continue As Global.IAW.controls.IAWHyperLinkButton

    '''<summary>
    '''btn_4_hidden control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_4_hidden As Global.System.Web.UI.WebControls.Button
End Class
