'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Secure_Login

    '''<summary>
    '''div_login control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents div_login As Global.IAW.controls.IAWPanel

    '''<summary>
    '''msgAbove control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents msgAbove As Global.IAW.controls.IAWLabel

    '''<summary>
    '''PNL_login control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PNL_login As Global.IAW.controls.IAWPanel

    '''<summary>
    '''Login2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Login2 As Global.IAW.controls.IAWLogin

    '''<summary>
    '''msg_lockedout control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents msg_lockedout As Global.IAW.controls.IawMessage

    '''<summary>
    '''msgBelow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents msgBelow As Global.IAW.controls.IAWLabel

    '''<summary>
    '''div_agreement control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents div_agreement As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''span_agreement control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents span_agreement As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''btn_agreement control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_agreement As Global.IAW.controls.IAWHyperLinkButton

    '''<summary>
    '''lblMsg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMsg As Global.IAW.controls.IAWLabel
End Class
