'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Diagram

    '''<summary>
    '''hdnGoJsKey control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnGoJsKey As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''surround_panel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents surround_panel As Global.IAW.controls.IAWPanel

    '''<summary>
    '''hdnButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnButton As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnHide control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnHide As Global.IAW.controls.IAWLabel

    '''<summary>
    '''txtAEAfilter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAEAfilter As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''btnShow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnShow As Global.IAW.controls.IAWLabel

    '''<summary>
    '''btnFirstChart control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnFirstChart As Global.IAW.controls.IAWHyperLinkButton

    '''<summary>
    '''btnEarlierChart control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnEarlierChart As Global.IAW.controls.IAWHyperLinkButton

    '''<summary>
    '''btnLaterChart control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnLaterChart As Global.IAW.controls.IAWHyperLinkButton

    '''<summary>
    '''btnLastChart control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnLastChart As Global.IAW.controls.IAWHyperLinkButton

    '''<summary>
    '''btnChangeDirection control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnChangeDirection As Global.IAW.controls.IAWLabel

    '''<summary>
    '''btnZoomFit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnZoomFit As Global.IAW.controls.IAWLabel

    '''<summary>
    '''btnCentreTop control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCentreTop As Global.IAW.controls.IAWLabel

    '''<summary>
    '''btnCentreRootNode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCentreRootNode As Global.IAW.controls.IAWLabel

    '''<summary>
    '''btnShowMagnifier control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnShowMagnifier As Global.IAW.controls.IAWLabel

    '''<summary>
    '''btnDownloadPDF control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDownloadPDF As Global.IAW.controls.IAWLabel

    '''<summary>
    '''txtSearchModel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSearchModel As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''btnModelSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnModelSearch As Global.IAW.controls.IAWLabel

    '''<summary>
    '''btnModelSearchClear control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnModelSearchClear As Global.IAW.controls.IAWLabel

    '''<summary>
    '''btnModelSave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnModelSave As Global.IAW.controls.IAWLabel

    '''<summary>
    '''btnModelUndo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnModelUndo As Global.IAW.controls.IAWLabel

    '''<summary>
    '''btnModelBackToList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnModelBackToList As Global.IAW.controls.IAWHyperLinkButton

    '''<summary>
    '''menu_make_group control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents menu_make_group As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''menu_modal_setting control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents menu_modal_setting As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''menu_make_vacant control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents menu_make_vacant As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''menu_node_setting control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents menu_node_setting As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''menu_add_text control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents menu_add_text As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''menu_assistant_on control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents menu_assistant_on As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''menu_assistant_off control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents menu_assistant_off As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''menu_move_left control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents menu_move_left As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''menu_move_right control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents menu_move_right As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''menu_make_parent_group control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents menu_make_parent_group As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''menu_make_new_parent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents menu_make_new_parent As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''menu_make_child control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents menu_make_child As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''menu_down_to_parent_group control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents menu_down_to_parent_group As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''menu_up_to_parent_group control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents menu_up_to_parent_group As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''menu_link_settings control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents menu_link_settings As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''menu_expand_below control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents menu_expand_below As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''menu_collapse_below control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents menu_collapse_below As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''menu_delete_parent_group control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents menu_delete_parent_group As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''popModelSettings control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents popModelSettings As Global.IAW.controls.IAWPanel

    '''<summary>
    '''modelTabContainer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents modelTabContainer As Global.AjaxControlToolkit.TabContainer

    '''<summary>
    '''tpModelGeneral control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tpModelGeneral As Global.IAW.controls.IAWTabPanel

    '''<summary>
    '''IAWLabel34 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel34 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''ddlbChartBackgroundType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlbChartBackgroundType As Global.IAW.controls.IAWDropDownList

    '''<summary>
    '''IAWLabel35 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel35 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''ddlbChartBackgroundImage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlbChartBackgroundImage As Global.IAW.controls.IAWDropDownList

    '''<summary>
    '''IAWLabel48 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel48 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''ddlbChartBackgroundGradient control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlbChartBackgroundGradient As Global.IAW.controls.IAWDropDownList

    '''<summary>
    '''IAWLabel2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel2 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''txtChartBackgroundColour control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtChartBackgroundColour As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''cbShowPhotos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbShowPhotos As Global.IAW.controls.IAWCheckBox

    '''<summary>
    '''IAWLabel19 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel19 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''ddlbImagePosition control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlbImagePosition As Global.IAW.controls.IAWDropDownList

    '''<summary>
    '''IAWLabel32 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel32 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''ddlbImageShape control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlbImageShape As Global.IAW.controls.IAWDropDownList

    '''<summary>
    '''IAWLabel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel1 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''numButtonImageHeight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents numButtonImageHeight As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''sliderButtonImageHeight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sliderButtonImageHeight As Global.AjaxControlToolkit.SliderExtender

    '''<summary>
    '''labButtonImageHeight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents labButtonImageHeight As Global.IAW.controls.IAWLabel

    '''<summary>
    '''lblRelationshipLinesTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRelationshipLinesTitle As Global.IAW.controls.IAWLabel

    '''<summary>
    '''IAWLabel75 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel75 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''txtModelLinkColour control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtModelLinkColour As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''txtModelLinkHover control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtModelLinkHover As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''IAWLabel5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel5 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''txtModelLinkTooltipFg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtModelLinkTooltipFg As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''txtModelLinkTooltipBg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtModelLinkTooltipBg As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''txtModelLinkTooltipBorder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtModelLinkTooltipBorder As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''IAWLabel76 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel76 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''numModelLinkWidth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents numModelLinkWidth As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''slideLinkWidth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents slideLinkWidth As Global.AjaxControlToolkit.SliderExtender

    '''<summary>
    '''labModelLinkWidth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents labModelLinkWidth As Global.IAW.controls.IAWLabel

    '''<summary>
    '''IAWLabel77 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel77 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''ddlbModelLinkStyle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlbModelLinkStyle As Global.IAW.controls.IAWDropDownList

    '''<summary>
    '''tpModelButtons control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tpModelButtons As Global.IAW.controls.IAWTabPanel

    '''<summary>
    '''IAWLabel87 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel87 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''rbButtonPositionLeft control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbButtonPositionLeft As Global.IAW.controls.IAWRadioButton

    '''<summary>
    '''rbButtonPositionBelow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbButtonPositionBelow As Global.IAW.controls.IAWRadioButton

    '''<summary>
    '''IAWLabel38 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel38 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''rbButtonFontSmall control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbButtonFontSmall As Global.IAW.controls.IAWRadioButton

    '''<summary>
    '''rbButtonFontMedium control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbButtonFontMedium As Global.IAW.controls.IAWRadioButton

    '''<summary>
    '''IAWLabel69 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel69 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''rbButtonShapeSquare control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbButtonShapeSquare As Global.IAW.controls.IAWRadioButton

    '''<summary>
    '''rbButtonShapeRounded control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbButtonShapeRounded As Global.IAW.controls.IAWRadioButton

    '''<summary>
    '''IAWLabel79 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel79 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''txtButtonTextColour control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtButtonTextColour As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''txtButtonBackgroundColour control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtButtonBackgroundColour As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''txtButtonBorderColour control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtButtonBorderColour As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''IAWLabel83 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel83 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''txtButtonTextHover control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtButtonTextHover As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''txtButtonBackgroundHover control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtButtonBackgroundHover As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''txtButtonBorderHover control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtButtonBorderHover As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''lblButtonDetailText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblButtonDetailText As Global.IAW.controls.IAWLabel

    '''<summary>
    '''lblButtonDetailTooltip control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblButtonDetailTooltip As Global.IAW.controls.IAWLabel

    '''<summary>
    '''txtButtonDetailText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtButtonDetailText As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''lblButtonNoteText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblButtonNoteText As Global.IAW.controls.IAWLabel

    '''<summary>
    '''lblButtonNoteTooltip control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblButtonNoteTooltip As Global.IAW.controls.IAWLabel

    '''<summary>
    '''txtButtonNoteText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtButtonNoteText As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''tpModelNode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tpModelNode As Global.IAW.controls.IAWTabPanel

    '''<summary>
    '''IAWLabel3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel3 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''txtNodefg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNodefg As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''txtNodeTxtBg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNodeTxtBg As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''txtNodebg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNodebg As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''txtBorderfg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBorderfg As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''cbTextBgBlock control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbTextBgBlock As Global.IAW.controls.IAWCheckBox

    '''<summary>
    '''IAWLabel6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel6 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''txtTTfg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTTfg As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''txtTTbg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTTbg As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''txtTTBorder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTTBorder As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''IAWLabel31 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel31 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''txtHighlightfg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtHighlightfg As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''txtHighlightbg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtHighlightbg As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''IAWLabel25 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel25 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''txtModelIconfg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtModelIconfg As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''txtModelIconHover control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtModelIconHover As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''cbModelShowShadow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbModelShowShadow As Global.IAW.controls.IAWCheckBox

    '''<summary>
    '''txtModelShadowColour control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtModelShadowColour As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''IAWLabel7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel7 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''numModelBoxWidth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents numModelBoxWidth As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''sliderModelBoxWidth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sliderModelBoxWidth As Global.AjaxControlToolkit.SliderExtender

    '''<summary>
    '''labModelBoxWidth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents labModelBoxWidth As Global.IAW.controls.IAWLabel

    '''<summary>
    '''IAWLabel4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel4 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''numModelBoxHeight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents numModelBoxHeight As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''sliderModelBoxHeight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sliderModelBoxHeight As Global.AjaxControlToolkit.SliderExtender

    '''<summary>
    '''labModelBoxHeight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents labModelBoxHeight As Global.IAW.controls.IAWLabel

    '''<summary>
    '''IAWLabel12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel12 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''rbModelCornerRectangle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbModelCornerRectangle As Global.IAW.controls.IAWRadioButton

    '''<summary>
    '''rbModelCornerRoundedRectangle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbModelCornerRoundedRectangle As Global.IAW.controls.IAWRadioButton

    '''<summary>
    '''tpModelFont control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tpModelFont As Global.IAW.controls.IAWTabPanel

    '''<summary>
    '''IAWLabel14 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel14 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''IAWLabel15 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel15 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''IAWLabel18 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel18 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''IAWLabel20 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel20 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''IAWLabel21 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel21 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''IAWLabel22 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel22 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''btnApplyModelSettings control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnApplyModelSettings As Global.IAW.controls.IAWHyperLinkButton

    '''<summary>
    '''btnCancelModelSettings control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancelModelSettings As Global.IAW.controls.IAWHyperLinkButton

    '''<summary>
    '''btnModelSettingsFake control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnModelSettingsFake As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''mpeModelSettingsForm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mpeModelSettingsForm As Global.AjaxControlToolkit.ModalPopupExtender

    '''<summary>
    '''popNodeSettings control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents popNodeSettings As Global.IAW.controls.IAWPanel

    '''<summary>
    '''nodeTabContainer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents nodeTabContainer As Global.AjaxControlToolkit.TabContainer

    '''<summary>
    '''tpNodeGeneral control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tpNodeGeneral As Global.IAW.controls.IAWTabPanel

    '''<summary>
    '''IAWLabel9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel9 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''txtNodeBoxfg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNodeBoxfg As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''txtNodeTextBg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNodeTextBg As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''txtNodeBoxbg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNodeBoxbg As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''txtNodeBorderfg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNodeBorderfg As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''cbNodeTextBgBlock control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbNodeTextBgBlock As Global.IAW.controls.IAWCheckBox

    '''<summary>
    '''cbNodeShowShadow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbNodeShowShadow As Global.IAW.controls.IAWCheckBox

    '''<summary>
    '''txtNodeShadowColour control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNodeShadowColour As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''IAWLabel28 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel28 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''txtNodeIconfg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNodeIconfg As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''txtNodeIconHover control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNodeIconHover As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''IAWLabel8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel8 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''numNodeBoxWidth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents numNodeBoxWidth As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''sliderNodeBoxWidth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sliderNodeBoxWidth As Global.AjaxControlToolkit.SliderExtender

    '''<summary>
    '''labNodeBoxWidth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents labNodeBoxWidth As Global.IAW.controls.IAWLabel

    '''<summary>
    '''IAWLabel10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel10 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''numNodeBoxHeight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents numNodeBoxHeight As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''sliderNodeBoxHeight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sliderNodeBoxHeight As Global.AjaxControlToolkit.SliderExtender

    '''<summary>
    '''labNodeBoxHeight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents labNodeBoxHeight As Global.IAW.controls.IAWLabel

    '''<summary>
    '''IAWLabel11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel11 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''rbNodeCornerRectangle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbNodeCornerRectangle As Global.IAW.controls.IAWRadioButton

    '''<summary>
    '''rbNodeCornerRoundedRectangle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbNodeCornerRoundedRectangle As Global.IAW.controls.IAWRadioButton

    '''<summary>
    '''IAWLabel23 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel23 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''numNodesAcross control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents numNodesAcross As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''SliderNodesAcross control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SliderNodesAcross As Global.AjaxControlToolkit.SliderExtender

    '''<summary>
    '''labNodesAcross control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents labNodesAcross As Global.IAW.controls.IAWLabel

    '''<summary>
    '''lblNodesAcrossInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNodesAcrossInfo As Global.IAW.controls.IAWLabel

    '''<summary>
    '''cbNodeShowPhoto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbNodeShowPhoto As Global.IAW.controls.IAWCheckBox

    '''<summary>
    '''numNodeImageHeight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents numNodeImageHeight As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''SliderNodeImageHeight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SliderNodeImageHeight As Global.AjaxControlToolkit.SliderExtender

    '''<summary>
    '''labNodeImageHeight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents labNodeImageHeight As Global.IAW.controls.IAWLabel

    '''<summary>
    '''tpNodeTeam control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tpNodeTeam As Global.IAW.controls.IAWTabPanel

    '''<summary>
    '''ddlbFont control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlbFont As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lblLines control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLines As Global.IAW.controls.IAWLabel

    '''<summary>
    '''lblGroupTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblGroupTitle As Global.IAW.controls.IAWLabel

    '''<summary>
    '''iUndoLine1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents iUndoLine1 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''txtTeamLine1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTeamLine1 As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''iUndoLine2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents iUndoLine2 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''txtTeamLine2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTeamLine2 As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''iUndoLine3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents iUndoLine3 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''txtTeamLine3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTeamLine3 As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''iUndoLine4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents iUndoLine4 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''txtTeamLine4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTeamLine4 As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''iUndoLine5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents iUndoLine5 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''txtTeamLine5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTeamLine5 As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''iUndoLine6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents iUndoLine6 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''txtTeamLine6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTeamLine6 As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''tpNodeNote control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tpNodeNote As Global.IAW.controls.IAWTabPanel

    '''<summary>
    '''IAWLabel16 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel16 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''txtTooltip control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTooltip As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''txtNodeTooltipfg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNodeTooltipfg As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''txtNodeTooltipbg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNodeTooltipbg As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''txtNodeTooltipBorder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNodeTooltipBorder As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''cbPrivateLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbPrivateLabel As Global.IAW.controls.IAWCheckBox

    '''<summary>
    '''tpNodeIcon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tpNodeIcon As Global.IAW.controls.IAWTabPanel

    '''<summary>
    '''rbLabelIcon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbLabelIcon As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''IAWLabel29 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel29 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''txtIconfg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtIconfg As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''txtIconbg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtIconbg As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''txtIconBorder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtIconBorder As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''IAWLabel30 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel30 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''rbIconSquare control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbIconSquare As Global.IAW.controls.IAWRadioButton

    '''<summary>
    '''rbIconCircle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbIconCircle As Global.IAW.controls.IAWRadioButton

    '''<summary>
    '''ddlbApplyOptions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlbApplyOptions As Global.IAW.controls.IAWDropDownList

    '''<summary>
    '''ddlbApplyTypes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlbApplyTypes As Global.IAW.controls.IAWDropDownList

    '''<summary>
    '''cbApplySizes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbApplySizes As Global.IAW.controls.IAWCheckBox

    '''<summary>
    '''btnApplyNodeSettings control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnApplyNodeSettings As Global.IAW.controls.IAWHyperLinkButton

    '''<summary>
    '''btnApplyNewNode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnApplyNewNode As Global.IAW.controls.IAWHyperLinkButton

    '''<summary>
    '''btnCancelNodeSettings control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancelNodeSettings As Global.IAW.controls.IAWHyperLinkButton

    '''<summary>
    '''btnApplyDefaults control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnApplyDefaults As Global.IAW.controls.IAWHyperLinkButton

    '''<summary>
    '''btnNodeSettingsFake control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnNodeSettingsFake As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''mpeNodeSettingsForm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mpeNodeSettingsForm As Global.AjaxControlToolkit.ModalPopupExtender

    '''<summary>
    '''popItemDetail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents popItemDetail As Global.IAW.controls.IAWPanel

    '''<summary>
    '''btnCancelItemDetail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancelItemDetail As Global.IAW.controls.IAWHyperLinkButton

    '''<summary>
    '''btnItemDetailFake control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnItemDetailFake As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''mpeItemDetailForm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mpeItemDetailForm As Global.AjaxControlToolkit.ModalPopupExtender

    '''<summary>
    '''popLinkSettings control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents popLinkSettings As Global.IAW.controls.IAWPanel

    '''<summary>
    '''IAWLabel13 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel13 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''txtLinkColour control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLinkColour As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''txtLinkHover control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLinkHover As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''IAWLabel17 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel17 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''numLinkWidth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents numLinkWidth As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''sliderLinkWidth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sliderLinkWidth As Global.AjaxControlToolkit.SliderExtender

    '''<summary>
    '''labLinkWidth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents labLinkWidth As Global.IAW.controls.IAWLabel

    '''<summary>
    '''IAWLabel24 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel24 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''ddlbLinkStyle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlbLinkStyle As Global.IAW.controls.IAWDropDownList

    '''<summary>
    '''IAWLabel26 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel26 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''txtLinkTooltipFg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLinkTooltipFg As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''txtLinkTooltipBg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLinkTooltipBg As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''txtLinkTooltipBorder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLinkTooltipBorder As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''IAWLabel27 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IAWLabel27 As Global.IAW.controls.IAWLabel

    '''<summary>
    '''txtLinkTooltip control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLinkTooltip As Global.IAW.controls.IAWTextbox

    '''<summary>
    '''ddlbApplyLinkOptions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlbApplyLinkOptions As Global.IAW.controls.IAWDropDownList

    '''<summary>
    '''btnApplyLinkSettings control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnApplyLinkSettings As Global.IAW.controls.IAWHyperLinkButton

    '''<summary>
    '''btnCancelLinkSettings control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancelLinkSettings As Global.IAW.controls.IAWHyperLinkButton

    '''<summary>
    '''btnLinkSettingsFake control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnLinkSettingsFake As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''mpeLinkSettingsForm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mpeLinkSettingsForm As Global.AjaxControlToolkit.ModalPopupExtender

    '''<summary>
    '''popUndo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents popUndo As Global.IAW.controls.IAWPanel

    '''<summary>
    '''lblUndoConfirm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUndoConfirm As Global.IAW.controls.IAWLabel

    '''<summary>
    '''btnUndoOk control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnUndoOk As Global.IAW.controls.IAWHyperLinkButton

    '''<summary>
    '''btnUndoCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnUndoCancel As Global.IAW.controls.IAWHyperLinkButton

    '''<summary>
    '''mpeUndo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mpeUndo As Global.AjaxControlToolkit.ModalPopupExtender
End Class
