move 1px.gif ..
move about.gif ..
move add.png ..
move alert_blank.gif ..
move alert_red.gif ..
move check2.gif ..
move collapse.jpg ..
move cross2.png ..
move delete.gif ..
move doc-icon-small.gif ..
move down_arrow_small.png ..
move excel-icon.png ..
move expand.jpg ..
move eye.png ..
move folder.gif ..
move html.gif ..
move info_error.gif ..
move left_arrow.png ..
move line.gif ..
move mail.png ..
move mail_forward.png ..
move mail_reply.png ..
move modify.png ..
move noeye.png ..
move noimage.jpg ..
move noimage_small.jpg ..
move paperclip.png ..
move partday.gif ..
move pdf-icon-small.gif ..
move pdf.png ..
move pdf_sprite.png ..
move printer-med.gif ..
move right_arrow.png ..
move search.png ..
move sort_down.gif ..
move sort_up.gif ..
move tick.gif ..
move tick2.png ..
move trans.gif ..
move trash.png ..
move up_arrow.png ..
move view_document.png ..
